// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAG6JoVPQj0LYeF3L0X56tXL1LVon1VC_A',
//     appId: '1:628059193303:web:81eaeff9a589fe2aaad592',
//     messagingSenderId: '628059193303',
//     projectId: 'expense-tracker-d0096',
//     authDomain: 'expense-tracker-d0096.firebaseapp.com',
//     storageBucket: 'expense-tracker-d0096.appspot.com',
//     measurementId: 'G-Q8LMH2X2K5',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAHJ1AJdPweYM5mcQdcSCWRGz_QaX4obYg',
//     appId: '1:628059193303:android:510271a4ea42fbd4aad592',
//     messagingSenderId: '628059193303',
//     projectId: 'expense-tracker-d0096',
//     storageBucket: 'expense-tracker-d0096.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCiO1Goqo9d_Dg03N97BM5PfKrt6BEtAug',
//     appId: '1:628059193303:ios:275103566d9ace63aad592',
//     messagingSenderId: '628059193303',
//     projectId: 'expense-tracker-d0096',
//     storageBucket: 'expense-tracker-d0096.appspot.com',
//     iosClientId: '628059193303-lpeho2fc2tg501qsukka6qjqd42h8v76.apps.googleusercontent.com',
//     iosBundleId: 'com.sunnydodti.expenseTracker',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCiO1Goqo9d_Dg03N97BM5PfKrt6BEtAug',
//     appId: '1:628059193303:ios:275103566d9ace63aad592',
//     messagingSenderId: '628059193303',
//     projectId: 'expense-tracker-d0096',
//     storageBucket: 'expense-tracker-d0096.appspot.com',
//     iosClientId: '628059193303-lpeho2fc2tg501qsukka6qjqd42h8v76.apps.googleusercontent.com',
//     iosBundleId: 'com.sunnydodti.expenseTracker',
//   );
// }
