name: expense_tracker
description: Flutter project for Expense tracker
version: 0.0.9-alpha

environment:
  sdk: ^3.6.0

dependencies:
  archive: ^4.0.2
  faker: ^2.2.0
  file_picker: ^8.1.7
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  intl: ^0.20.1
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.2.5

flutter:
  uses-material-design: true