name: expense_tracker
description: Flutter project for Expense tracker
version: 0.2.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  sqflite:
  path:
  path_provider:
  faker:
  provider:
  file_picker:
  logger:
  archive:
  share:
  permission_handler:
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - 'assets/'

  fonts:
    - family: Caveat
      fonts:
      - asset: fonts/Caveat/Caveat-Regular.ttf