name: expense_tracker
description: Flutter project for Expense tracker
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  intl: ^0.18.1
  universal_io: ^2.2.2
  currency_picker: ^2.0.16
  multiselect_formfield: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - 'assets/'
      
  fonts:
    - family: Caveat
      fonts:
      - asset: fonts/Caveat/Caveat-Regular.ttf